query GetPaymentList($claim_administrator_code: String) {
    claimAdmins(code: $claim_administrator_code) {
        edges {
            node {
                code
                healthFacility {
                    code
                    servicesPricelist {
                        details {
                            edges {
                                node {
                                    service {
                                        id
                                        code
                                        name
                                        price
                                        packagetype
                                        type
                                        careType
                                        manualPrice
                                        serviceserviceSet {
                                            service {
                                                id
                                                code
                                                name
                                            }
                                            qtyProvided
                                            priceAsked
                                        }
                                        servicesLinked {
                                            item {
                                                id
                                                code
                                                name
                                            }
                                            qtyProvided
                                            priceAsked
                                        }
                                    }
                                }
                            }
                        }
                    }
                    itemsPricelist {
                        details {
                            edges {
                                node {
                                    item {
                                        id
                                        code
                                        name
                                        price
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}