query GetServices ($offset: Int) {
  medicalServices(offset: $offset) {
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        id
        code
        name
        packagetype
        type
        price
        careType
        manualPrice
        serviceserviceSet {
          service {
            id
            code
            name
          }
          qtyProvided
          priceAsked
        }
        servicesLinked {
          item {
            id
            code
            name
          }
          qtyProvided
          priceAsked
        }
      }
    }
  }
}